# Generated by Django 3.2 on 2021-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='category',
            new_name='hotspot',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='hotspot',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='category',
            new_name='name',
        ),
    ]
