# Generated by Django 3.2 on 2021-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0002_auto_20210421_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
