# Generated by Django 3.2 on 2021-04-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0003_auto_20210421_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='hotspot',
        ),
        migrations.RemoveField(
            model_name='food',
            name='hotspot',
        ),
        migrations.DeleteModel(
            name='HotSpot',
        ),
    ]
