# Generated by Django 3.2 on 2021-04-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0005_auto_20210422_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='group',
            field=models.CharField(default='groups', max_length=100),
        ),
        migrations.AddField(
            model_name='drink',
            name='photo_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='group',
            field=models.CharField(default='groups', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='photo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
