# Generated by Django 3.2 on 2021-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0007_auto_20210423_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='tags',
            field=models.CharField(default='tags', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.CharField(default='tags', max_length=100),
        ),
    ]
