# Generated by Django 3.2 on 2021-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0008_auto_20210423_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
        migrations.CreateModel(
            name='HotSpotTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.TextField()),
                ('foodName', models.ManyToManyField(related_name='tags', related_query_name='tag', to='hipyelp.Food')),
            ],
        ),
    ]
