# Generated by Django 3.2 on 2021-04-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0010_auto_20210425_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktag',
            name='drinkName',
            field=models.ManyToManyField(related_name='drinkTags', related_query_name=' drinktag', to='hipyelp.Drink'),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='foodName',
            field=models.ManyToManyField(related_name='foodTags', related_query_name='foodtag', to='hipyelp.Food'),
        ),
    ]
