# Generated by Django 3.2 on 2021-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0011_auto_20210425_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinktag',
            name='tagName',
            field=models.TextField(default='dive'),
        ),
    ]
