# Generated by Django 3.2 on 2021-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0012_drinktag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktag',
            name='tagName',
            field=models.TextField(default=''),
        ),
    ]
