# Generated by Django 3.2 on 2021-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0014_rename_tagname_drinktag_drinktagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktag',
            name='drinktagName',
            field=models.TextField(),
        ),
    ]
