# Generated by Django 3.2 on 2021-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0016_rename_drinktagname_drinktag_tagname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinktag',
            old_name='tagName',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='foodtag',
            old_name='tagName',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='drink',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
    ]
