# Generated by Django 3.2 on 2021-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0017_auto_20210425_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinktag',
            name='test',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='foodtag',
            name='test',
            field=models.CharField(default='', max_length=100),
        ),
    ]
