# Generated by Django 3.2 on 2021-04-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0017_auto_20210426_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinktag',
            name='tags',
        ),
        migrations.AddField(
            model_name='drinktag',
            name='tagname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
