# Generated by Django 3.2 on 2021-04-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0018_auto_20210426_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktag',
            name='tagname',
            field=models.CharField(max_length=20),
        ),
    ]
