# Generated by Django 3.2 on 2021-04-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0019_auto_20210425_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='drinktag',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Dtag',
        ),
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='foodtag',
            name='tags',
        ),
        migrations.AddField(
            model_name='foodtag',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='hipyelp.food'),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='DrinkTag',
        ),
        migrations.DeleteModel(
            name='Ftag',
        ),
    ]
