# Generated by Django 3.2 on 2021-04-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0020_auto_20210426_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
    ]
