# Generated by Django 3.2 on 2021-04-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0020_auto_20210425_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtag',
            old_name='test',
            new_name='tags',
        ),
    ]
