# Generated by Django 3.2 on 2021-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0021_rename_test_foodtag_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtag',
            name='food',
        ),
        migrations.AddField(
            model_name='foodtag',
            name='foodName',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='hipyelp.Food'),
        ),
        migrations.AddField(
            model_name='foodtag',
            name='tagname',
            field=models.TextField(default=''),
        ),
    ]
