# Generated by Django 3.2 on 2021-04-26 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0022_auto_20210426_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtag',
            name='foodName',
        ),
        migrations.AddField(
            model_name='drink',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='DrinkTag',
        ),
        migrations.DeleteModel(
            name='FoodTag',
        ),
    ]
