# Generated by Django 3.2 on 2021-04-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0023_alter_foodtag_tagname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtag',
            name='foodName',
        ),
        migrations.RemoveField(
            model_name='foodtag',
            name='tagname',
        ),
        migrations.RemoveField(
            model_name='foodtag',
            name='tags',
        ),
        migrations.AddField(
            model_name='foodtag',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='hipyelp.food'),
        ),
    ]
