# Generated by Django 3.2 on 2021-04-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0024_auto_20210425_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodtag',
            name='tag',
        ),
        migrations.AddField(
            model_name='foodtag',
            name='foodtag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='foodtags', to='hipyelp.food'),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fuckingtags', to='hipyelp.Tag'),
        ),
    ]
