# Generated by Django 3.2 on 2021-04-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0025_auto_20210425_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
        migrations.DeleteModel(
            name='FoodTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
