# Generated by Django 3.2 on 2021-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0026_auto_20210425_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.CharField(default='tags', max_length=20),
        ),
    ]
