# Generated by Django 3.2 on 2021-04-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0027_food_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
    ]
