# Generated by Django 3.2 on 2021-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0028_alter_food_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
    ]
