# Generated by Django 3.2 on 2021-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipyelp', '0029_auto_20210425_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.CharField(default='tags', max_length=20),
        ),
    ]
